# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: likeservice.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'likeservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11likeservice.proto\x12\x0blikeservice\"%\n\x0fGetLikesRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"\'\n\x10GetLikesResponse\x12\x13\n\x0blikes_count\x18\x01 \x01(\x05\"$\n\x0e\x41\x64\x64LikeRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"\"\n\x0f\x41\x64\x64LikeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9d\x01\n\x0cLikesService\x12G\n\x08GetLikes\x12\x1c.likeservice.GetLikesRequest\x1a\x1d.likeservice.GetLikesResponse\x12\x44\n\x07\x41\x64\x64Like\x12\x1b.likeservice.AddLikeRequest\x1a\x1c.likeservice.AddLikeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'likeservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETLIKESREQUEST']._serialized_start=34
  _globals['_GETLIKESREQUEST']._serialized_end=71
  _globals['_GETLIKESRESPONSE']._serialized_start=73
  _globals['_GETLIKESRESPONSE']._serialized_end=112
  _globals['_ADDLIKEREQUEST']._serialized_start=114
  _globals['_ADDLIKEREQUEST']._serialized_end=150
  _globals['_ADDLIKERESPONSE']._serialized_start=152
  _globals['_ADDLIKERESPONSE']._serialized_end=186
  _globals['_LIKESSERVICE']._serialized_start=189
  _globals['_LIKESSERVICE']._serialized_end=346
# @@protoc_insertion_point(module_scope)
