# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import likeservice_pb2 as likeservice__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in likeservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LikesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLikes = channel.unary_unary(
                '/likeservice.LikesService/GetLikes',
                request_serializer=likeservice__pb2.GetLikesRequest.SerializeToString,
                response_deserializer=likeservice__pb2.GetLikesResponse.FromString,
                _registered_method=True)
        self.AddLike = channel.unary_unary(
                '/likeservice.LikesService/AddLike',
                request_serializer=likeservice__pb2.AddLikeRequest.SerializeToString,
                response_deserializer=likeservice__pb2.AddLikeResponse.FromString,
                _registered_method=True)


class LikesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLikes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddLike(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LikesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLikes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLikes,
                    request_deserializer=likeservice__pb2.GetLikesRequest.FromString,
                    response_serializer=likeservice__pb2.GetLikesResponse.SerializeToString,
            ),
            'AddLike': grpc.unary_unary_rpc_method_handler(
                    servicer.AddLike,
                    request_deserializer=likeservice__pb2.AddLikeRequest.FromString,
                    response_serializer=likeservice__pb2.AddLikeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'likeservice.LikesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('likeservice.LikesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LikesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLikes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likeservice.LikesService/GetLikes',
            likeservice__pb2.GetLikesRequest.SerializeToString,
            likeservice__pb2.GetLikesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddLike(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likeservice.LikesService/AddLike',
            likeservice__pb2.AddLikeRequest.SerializeToString,
            likeservice__pb2.AddLikeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
