apiVersion: apps/v1
kind: Deployment
metadata:
  name: likeservice
  labels:
    app: likeservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: likeservice
  template:
    metadata:
      labels:
        app: likeservice
    spec:
      containers:
      - name: likeservice
        image: likeservice:latest # Replace with your registry image
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: likeservice
spec:
  selector:
    app: likeservice
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
