apiVersion: apps/v1
kind: Deployment
metadata:
  name: likeservice
  labels:
    app: likeservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: likeservice
  template:
    metadata:
      labels:
        app: likeservice
    spec:
      containers:
      - name: server
        image: likeservice  # Replace with your registry image
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
#        readinessProbe:
#          grpc:
#            port: 8080
#          periodSeconds: 5
#          initialDelaySeconds: 5
#          timeoutSeconds: 2
#          failureThreshold: 3
#        livenessProbe:
#          grpc:
#            port: 8080
#          periodSeconds: 5
#          initialDelaySeconds: 5
#          timeoutSeconds: 2
#          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: likeservice
  labels: 
    app: likeservice
spec:
  type: ClusterIP
  selector:
    app: likeservice
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: likeservice
