# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/likeservice.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'protos/likeservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protos/likeservice.proto\x12\x0blikeservice\"9\n\x0fHasLikedRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"!\n\x10HasLikedResponse\x12\r\n\x05liked\x18\x01 \x01(\x08\"%\n\x0fGetLikesRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"\'\n\x10GetLikesResponse\x12\x13\n\x0blikes_count\x18\x01 \x01(\x05\"8\n\x0e\x41\x64\x64LikeRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"\"\n\x0f\x41\x64\x64LikeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xe6\x01\n\x0cLikesService\x12G\n\x08GetLikes\x12\x1c.likeservice.GetLikesRequest\x1a\x1d.likeservice.GetLikesResponse\x12\x44\n\x07\x41\x64\x64Like\x12\x1b.likeservice.AddLikeRequest\x1a\x1c.likeservice.AddLikeResponse\x12G\n\x08HasLiked\x12\x1c.likeservice.HasLikedRequest\x1a\x1d.likeservice.HasLikedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.likeservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HASLIKEDREQUEST']._serialized_start=41
  _globals['_HASLIKEDREQUEST']._serialized_end=98
  _globals['_HASLIKEDRESPONSE']._serialized_start=100
  _globals['_HASLIKEDRESPONSE']._serialized_end=133
  _globals['_GETLIKESREQUEST']._serialized_start=135
  _globals['_GETLIKESREQUEST']._serialized_end=172
  _globals['_GETLIKESRESPONSE']._serialized_start=174
  _globals['_GETLIKESRESPONSE']._serialized_end=213
  _globals['_ADDLIKEREQUEST']._serialized_start=215
  _globals['_ADDLIKEREQUEST']._serialized_end=271
  _globals['_ADDLIKERESPONSE']._serialized_start=273
  _globals['_ADDLIKERESPONSE']._serialized_end=307
  _globals['_LIKESSERVICE']._serialized_start=310
  _globals['_LIKESSERVICE']._serialized_end=540
# @@protoc_insertion_point(module_scope)
